FROM node:20-alpine AS base

# Install project dependences 
FROM base as deps
WORKDIR /app
COPY package.json ./
RUN npm ci

# Build and run the project
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
